### ISSUE TITLE
Erreurs lors de l'utilisation du docker Mongo/ES

### ISSUE THREAD

**Issue by naholyr** [SciencesPo/isari#17]
En l'état je manque d'informations pour utiliser le container correctement je pense.

J'utilise les commandes suivantes :

* Démarrage : `docker-compose -p isari up`
* Suppression : `docker-compose down --rmi local --remove-orphans --volumes`

Ensuite je ne sais pas dans quoi ajouter des données pour que l'indexation se fasse correctement. J'ai trouvé dans la config `MONGO_INCLUDES=people,organisation,activity` mais ça signifie qu'il indexe les données des BDD people, organisation, et activity. Je pense que la bonne option serait `isari.people,isari.organization,isari.activity` (y a-t-il une possibilité de changer le nom de la BDD à la volée, pour bosser sur `isari-dev` ou `isari-test` au besoin ?).

Ceci étant j'ai done ajouté de la donnée dans la base `people` pour tester:

```sh
mongo

> use people
> db.people.save({ name: 'John' })
```

Je vois bien plein d'activité dans le docker, mais ça n'a pas l'air d'être de bonnes nouvelles (j'ai indiqué les couleurs apparaissant dans la console, je ne sais pas si ça indique des niveaux de logs ou si c'est simplement un choix arbitraire de docker pour distinguer les logs de différentes sources) :

```
(en bleu clair)
index_1       | [2016-10-06 09:21:33,184][WARN ][cluster.routing.allocation.decider] [Feron] high disk watermark [90%] exceeded on [2q7_vNF4Rn25_3SY_8sfZg][Feron][/usr/share/elasticsearch/data/elasticsearch/nodes/0] free: 1.6gb[8.8%], shards will be relocated away from this node

(en violet)
connector_1   | 2016-10-06 09:21:33,781 [ERROR] mongo_connector.oplog_manager:488 - OplogThread: caught exception during bulk upsert, re-upserting documents serially
connector_1   | Traceback (most recent call last):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 485, in upsert_all
connector_1   |     dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/util.py", line 32, in wrapped
connector_1   |     return f(*args, **kwargs)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 190, in bulk_upsert
connector_1   |     for ok, resp in responses:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 159, in streaming_bulk
connector_1   |     for bulk_actions in _chunk_actions(actions, chunk_size, max_chunk_bytes, client.transport.serializer):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 53, in _chunk_actions
connector_1   |     for action, data in actions:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 156, in docs_to_upsert
connector_1   |     for doc in docs:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 427, in docs_to_dump
connector_1   |     database, coll = namespace.split('.', 1)
connector_1   | ValueError: not enough values to unpack (expected 2, got 1)
connector_1   | 2016-10-06 09:21:33,810 [CRITICAL] mongo_connector.oplog_manager:549 - Exception during collection dump
connector_1   | Traceback (most recent call last):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 485, in upsert_all
connector_1   |     dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/util.py", line 32, in wrapped
connector_1   |     return f(*args, **kwargs)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 190, in bulk_upsert
connector_1   |     for ok, resp in responses:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 159, in streaming_bulk
connector_1   |     for bulk_actions in _chunk_actions(actions, chunk_size, max_chunk_bytes, client.transport.serializer):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 53, in _chunk_actions
connector_1   |     for action, data in actions:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 156, in docs_to_upsert
connector_1   |     for doc in docs:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 427, in docs_to_dump
connector_1   |     database, coll = namespace.split('.', 1)
connector_1   | ValueError: not enough values to unpack (expected 2, got 1)
connector_1   | 
connector_1   | During handling of the above exception, another exception occurred:
connector_1   | 
connector_1   | Traceback (most recent call last):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 501, in do_dump
connector_1   |     upsert_all(dm)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 491, in upsert_all
connector_1   |     upsert_each(dm)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 463, in upsert_each
connector_1   |     for num, doc in enumerate(docs_to_dump(namespace)):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 427, in docs_to_dump
connector_1   |     database, coll = namespace.split('.', 1)
connector_1   | ValueError: not enough values to unpack (expected 2, got 1)
connector_1   | 2016-10-06 09:21:33,811 [ERROR] mongo_connector.oplog_manager:557 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient(host=['db:27017'], document_class=dict, tz_aware=True, connect=True, replicaset='rs2es'), 'local'), 'oplog.rs')
connector_1   | 2016-10-06 09:21:34,164 [ERROR] mongo_connector.connector:302 - MongoConnector: OplogThread <OplogThread(Thread-2, started 140374963817136)> unexpectedly stopped! Shutting down
connector_1   | 2016-10-06 09:21:34,165 [INFO] mongo_connector.connector:359 - MongoConnector: Stopping all OplogThreads

(en jaune)
db_1          | 2016-10-06T09:21:36.921+0000 I NETWORK  [conn4] end connection 172.18.0.5:42782 (2 connections now open)
db_1          | 2016-10-06T09:21:36.921+0000 I NETWORK  [conn5] end connection 172.18.0.5:42786 (2 connections now open)
db_1          | 2016-10-06T09:21:38.212+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.5:39334 #7 (2 connections now open)
db_1          | 2016-10-06T09:21:38.217+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.5:39336 #8 (3 connections now open)
db_1          | 2016-10-06T09:21:38.228+0000 I NETWORK  [conn7] end connection 172.18.0.5:39334 (2 connections now open)
db_1          | 2016-10-06T09:21:38.229+0000 I NETWORK  [conn8] end connection 172.18.0.5:39336 (1 connection now open)
db_1          | 2016-10-06T09:21:38.237+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.5:39338 #9 (2 connections now open)
db_1          | 2016-10-06T09:21:38.243+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.5:39340 #10 (3 connections now open)
db_1          | 2016-10-06T09:21:41.253+0000 I NETWORK  [conn9] end connection 172.18.0.5:39338 (2 connections now open)
db_1          | 2016-10-06T09:21:41.253+0000 I NETWORK  [conn10] end connection 172.18.0.5:39340 (2 connections now open)

(en violet)
isari_connector_1 exited with code 0

(en rouge)
connector_1   | 2016-10-06 09:18:26,337 [INFO] mongo_connector.connector:1044 - Beginning Mongo Connector
connector_1   | 2016-10-06 09:18:26,337 [WARNING] mongo_connector.connector:116 - MongoConnector: Can't find oplog.timestamp, attempting to create an empty progress log
connector_1   | 2016-10-06 09:18:26,339 [INFO] mongo_connector.connector:223 - MongoConnector: Empty oplog progress file.
connector_1   | 2016-10-06 09:18:26,353 [INFO] mongo_connector.oplog_manager:89 - OplogThread: Initializing oplog thread
connector_1   | 2016-10-06 09:18:26,858 [INFO] mongo_connector.connector:295 - MongoConnector: Starting connection thread MongoClient(host=['db:27017'], document_class=dict, tz_aware=True, connect=True, replicaset='rs2es')
connector_1   | 2016-10-06 09:21:33,781 [ERROR] mongo_connector.oplog_manager:488 - OplogThread: caught exception during bulk upsert, re-upserting documents serially
connector_1   | Traceback (most recent call last):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 485, in upsert_all
connector_1   |     dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/util.py", line 32, in wrapped
connector_1   |     return f(*args, **kwargs)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 190, in bulk_upsert
connector_1   |     for ok, resp in responses:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 159, in streaming_bulk
connector_1   |     for bulk_actions in _chunk_actions(actions, chunk_size, max_chunk_bytes, client.transport.serializer):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 53, in _chunk_actions
connector_1   |     for action, data in actions:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 156, in docs_to_upsert
connector_1   |     for doc in docs:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 427, in docs_to_dump
connector_1   |     database, coll = namespace.split('.', 1)
connector_1   | ValueError: not enough values to unpack (expected 2, got 1)
connector_1   | 2016-10-06 09:21:33,810 [CRITICAL] mongo_connector.oplog_manager:549 - Exception during collection dump
connector_1   | Traceback (most recent call last):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 485, in upsert_all
connector_1   |     dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/util.py", line 32, in wrapped
connector_1   |     return f(*args, **kwargs)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 190, in bulk_upsert
connector_1   |     for ok, resp in responses:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 159, in streaming_bulk
connector_1   |     for bulk_actions in _chunk_actions(actions, chunk_size, max_chunk_bytes, client.transport.serializer):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 53, in _chunk_actions
connector_1   |     for action, data in actions:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 156, in docs_to_upsert
connector_1   |     for doc in docs:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 427, in docs_to_dump
connector_1   |     database, coll = namespace.split('.', 1)
connector_1   | ValueError: not enough values to unpack (expected 2, got 1)
connector_1   | 
connector_1   | During handling of the above exception, another exception occurred:
connector_1   | 
connector_1   | Traceback (most recent call last):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 501, in do_dump
connector_1   |     upsert_all(dm)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 491, in upsert_all
connector_1   |     upsert_each(dm)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 463, in upsert_each
connector_1   |     for num, doc in enumerate(docs_to_dump(namespace)):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 427, in docs_to_dump
connector_1   |     database, coll = namespace.split('.', 1)
connector_1   | ValueError: not enough values to unpack (expected 2, got 1)
connector_1   | 2016-10-06 09:21:33,811 [ERROR] mongo_connector.oplog_manager:557 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient(host=['db:27017'], document_class=dict, tz_aware=True, connect=True, replicaset='rs2es'), 'local'), 'oplog.rs')
connector_1   | 2016-10-06 09:21:34,164 [ERROR] mongo_connector.connector:302 - MongoConnector: OplogThread <OplogThread(Thread-2, started 140374963817136)> unexpectedly stopped! Shutting down
connector_1   | 2016-10-06 09:21:34,165 [INFO] mongo_connector.connector:359 - MongoConnector: Stopping all OplogThreads
connector_1   | 2016-10-06 09:21:38,202 [INFO] mongo_connector.connector:1044 - Beginning Mongo Connector
connector_1   | 2016-10-06 09:21:38,209 [INFO] mongo_connector.connector:223 - MongoConnector: Empty oplog progress file.
connector_1   | 2016-10-06 09:21:38,234 [INFO] mongo_connector.oplog_manager:89 - OplogThread: Initializing oplog thread
connector_1   | 2016-10-06 09:21:38,249 [INFO] mongo_connector.connector:295 - MongoConnector: Starting connection thread MongoClient(host=['db:27017'], document_class=dict, tz_aware=True, connect=True, replicaset='rs2es')
connector_1   | 2016-10-06 09:21:38,258 [ERROR] mongo_connector.oplog_manager:488 - OplogThread: caught exception during bulk upsert, re-upserting documents serially
connector_1   | Traceback (most recent call last):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 485, in upsert_all
connector_1   |     dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/util.py", line 32, in wrapped
connector_1   |     return f(*args, **kwargs)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 190, in bulk_upsert
connector_1   |     for ok, resp in responses:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 159, in streaming_bulk
connector_1   |     for bulk_actions in _chunk_actions(actions, chunk_size, max_chunk_bytes, client.transport.serializer):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 53, in _chunk_actions
connector_1   |     for action, data in actions:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 156, in docs_to_upsert
connector_1   |     for doc in docs:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 427, in docs_to_dump
connector_1   |     database, coll = namespace.split('.', 1)
connector_1   | ValueError: not enough values to unpack (expected 2, got 1)
connector_1   | 2016-10-06 09:21:38,264 [CRITICAL] mongo_connector.oplog_manager:549 - Exception during collection dump
connector_1   | Traceback (most recent call last):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 485, in upsert_all
connector_1   |     dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/util.py", line 32, in wrapped
connector_1   |     return f(*args, **kwargs)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 190, in bulk_upsert
connector_1   |     for ok, resp in responses:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 159, in streaming_bulk
connector_1   |     for bulk_actions in _chunk_actions(actions, chunk_size, max_chunk_bytes, client.transport.serializer):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 53, in _chunk_actions
connector_1   |     for action, data in actions:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 156, in docs_to_upsert
connector_1   |     for doc in docs:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 427, in docs_to_dump
connector_1   |     database, coll = namespace.split('.', 1)
connector_1   | ValueError: not enough values to unpack (expected 2, got 1)
connector_1   | 
connector_1   | During handling of the above exception, another exception occurred:
connector_1   | 
connector_1   | Traceback (most recent call last):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 501, in do_dump
connector_1   |     upsert_all(dm)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 491, in upsert_all
connector_1   |     upsert_each(dm)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 463, in upsert_each
connector_1   |     for num, doc in enumerate(docs_to_dump(namespace)):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 427, in docs_to_dump
connector_1   |     database, coll = namespace.split('.', 1)
connector_1   | ValueError: not enough values to unpack (expected 2, got 1)
connector_1   | 2016-10-06 09:21:38,267 [ERROR] mongo_connector.oplog_manager:557 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient(host=['db:27017'], document_class=dict, tz_aware=True, connect=True, replicaset='rs2es'), 'local'), 'oplog.rs')
connector_1   | 2016-10-06 09:21:39,256 [ERROR] mongo_connector.connector:302 - MongoConnector: OplogThread <OplogThread(Thread-2, started 140256417118896)> unexpectedly stopped! Shutting down
connector_1   | 2016-10-06 09:21:39,257 [INFO] mongo_connector.connector:359 - MongoConnector: Stopping all OplogThreads
connector_1   | 2016-10-06 09:21:41,983 [INFO] mongo_connector.connector:1044 - Beginning Mongo Connector
connector_1   | 2016-10-06 09:21:41,985 [INFO] mongo_connector.connector:223 - MongoConnector: Empty oplog progress file.

(en jaune)
db_1          | 2016-10-06T09:21:41.985+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.5:39854 #11 (2 connections now open)
db_1          | 2016-10-06T09:21:41.986+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.5:39856 #12 (3 connections now open)
db_1          | 2016-10-06T09:21:41.987+0000 I NETWORK  [conn11] end connection 172.18.0.5:39854 (2 connections now open)
db_1          | 2016-10-06T09:21:41.987+0000 I NETWORK  [conn12] end connection 172.18.0.5:39856 (2 connections now open)

(en rouge)
connector_1   | 2016-10-06 09:21:41,988 [INFO] mongo_connector.oplog_manager:89 - OplogThread: Initializing oplog thread

(en jaune)
db_1          | 2016-10-06T09:21:41.989+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.5:39858 #13 (2 connections now open)
db_1          | 2016-10-06T09:21:41.990+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.5:39860 #14 (3 connections now open)

(en rouge)
connector_1   | 2016-10-06 09:21:41,991 [INFO] mongo_connector.connector:295 - MongoConnector: Starting connection thread MongoClient(host=['db:27017'], document_class=dict, tz_aware=True, connect=True, replicaset='rs2es')
connector_1   | 2016-10-06 09:21:41,993 [ERROR] mongo_connector.oplog_manager:488 - OplogThread: caught exception during bulk upsert, re-upserting documents serially
connector_1   | Traceback (most recent call last):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 485, in upsert_all
connector_1   |     dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/util.py", line 32, in wrapped
connector_1   |     return f(*args, **kwargs)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 190, in bulk_upsert
connector_1   |     for ok, resp in responses:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 159, in streaming_bulk
connector_1   |     for bulk_actions in _chunk_actions(actions, chunk_size, max_chunk_bytes, client.transport.serializer):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 53, in _chunk_actions
connector_1   |     for action, data in actions:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 156, in docs_to_upsert
connector_1   |     for doc in docs:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 427, in docs_to_dump
connector_1   |     database, coll = namespace.split('.', 1)
connector_1   | ValueError: not enough values to unpack (expected 2, got 1)
connector_1   | 2016-10-06 09:21:41,994 [CRITICAL] mongo_connector.oplog_manager:549 - Exception during collection dump
connector_1   | Traceback (most recent call last):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 485, in upsert_all
connector_1   |     dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/util.py", line 32, in wrapped
connector_1   |     return f(*args, **kwargs)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 190, in bulk_upsert
connector_1   |     for ok, resp in responses:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 159, in streaming_bulk
connector_1   |     for bulk_actions in _chunk_actions(actions, chunk_size, max_chunk_bytes, client.transport.serializer):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 53, in _chunk_actions
connector_1   |     for action, data in actions:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 156, in docs_to_upsert
connector_1   |     for doc in docs:
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 427, in docs_to_dump
connector_1   |     database, coll = namespace.split('.', 1)
connector_1   | ValueError: not enough values to unpack (expected 2, got 1)
connector_1   | 
connector_1   | During handling of the above exception, another exception occurred:
connector_1   | 
connector_1   | Traceback (most recent call last):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 501, in do_dump
connector_1   |     upsert_all(dm)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 491, in upsert_all
connector_1   |     upsert_each(dm)
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 463, in upsert_each
connector_1   |     for num, doc in enumerate(docs_to_dump(namespace)):
connector_1   |   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 427, in docs_to_dump
connector_1   |     database, coll = namespace.split('.', 1)
connector_1   | ValueError: not enough values to unpack (expected 2, got 1)
connector_1   | 2016-10-06 09:21:41,994 [ERROR] mongo_connector.oplog_manager:557 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient(host=['db:27017'], document_class=dict, tz_aware=True, connect=True, replicaset='rs2es'), 'local'), 'oplog.rs')
connector_1   | 2016-10-06 09:21:42,993 [ERROR] mongo_connector.connector:302 - MongoConnector: OplogThread <OplogThread(Thread-2, started 140071577344688)> unexpectedly stopped! Shutting down
connector_1   | 2016-10-06 09:21:42,993 [INFO] mongo_connector.connector:359 - MongoConnector: Stopping all OplogThreads

(en jaune)
db_1          | 2016-10-06T09:21:45.001+0000 I NETWORK  [conn13] end connection 172.18.0.5:39858 (2 connections now open)
db_1          | 2016-10-06T09:21:45.001+0000 I NETWORK  [conn14] end connection 172.18.0.5:39860 (2 connections now open)
db_1          | 2016-10-06T09:21:45.842+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.5:40374 #15 (2 connections now open)
db_1          | 2016-10-06T09:21:45.843+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.5:40376 #16 (3 connections now open)
db_1          | 2016-10-06T09:21:45.844+0000 I NETWORK  [conn15] end connection 172.18.0.5:40374 (2 connections now open)
db_1          | 2016-10-06T09:21:45.844+0000 I NETWORK  [conn16] end connection 172.18.0.5:40376 (2 connections now open)
db_1          | 2016-10-06T09:21:45.845+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.5:40378 #17 (2 connections now open)
db_1          | 2016-10-06T09:21:45.846+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.5:40380 #18 (3 connections now open)
db_1          | 2016-10-06T09:21:48.857+0000 I NETWORK  [conn18] end connection 172.18.0.5:40380 (2 connections now open)
db_1          | 2016-10-06T09:21:48.857+0000 I NETWORK  [conn17] end connection 172.18.0.5:40378 (2 connections now open)
```

Ça tourne en boucle comme ça. Je n'ai aucune indice créé dans ES.

**Comment by naholyr** [comment]
Comme je vois beaucoup d'erreurs liées à l'espace disque j'essaie de faire de la place, j'ai 30 Go à libérer je pense que ça devrait suffire mais ça prend du temps… des news quand j'ai fini

**Comment by paulgirard** [comment]
Alors dans l'ordre : 
- il faut en effet nommer les collections qui seront indexées dans EA en db.collection donc comme tu le proposes isari.people,isari.organization,isari.activity
- pour la question dev/prod, gardons l'image actuelle pour le dev uniquement. L'image docker de prod sera différente puisqu'elle intégrera le node.
- mongo-connector va déverser dans EA totues données présentes dans les collections pointées. Tu n'as rien de particulier à faire. Si ça marche tu verras tout un tas de requête de PUT dans EA dans les logs. Par ailleurs tu peux monitorer avec un bête requêtes à EA du style GET sur  localhost:9200/_cat/indices?v On aura bientôt un kibana pour faire un meilleur monitoring
- espace disque oui il faut pas mal d'espace disque surtout quand EA  va commencer à indexer.

Tient moi au courant une fois ménage fait

**Comment by naholyr** [comment]
C'était bien un problème d'espace disque. Au passage j'ai corrigé la config, on a 3 bases "isari", "isaridev" et "isaritest" (par souci de cohérence avec la config applicative pour éviter de mélanger les données par environnement tout en pouvant tester les différentes combinaisons) donc 9 entrées dans MONGO_INCLUDE.

Ça tourne sans souci.
