### ISSUE TITLE
Syntaxe layout.*.json : plusieurs Lignes de champs en Mode détaillé

### ISSUE THREAD

**Issue by paulgirard** [SciencesPo/isari#35]
``` json
{
    "fields": [
      ["researchTheme", "discipline", "methods"],
      ["erc", "aeres2012","hceres2017"],
      "free"
    ],
    "label": {
      "fr": "Tags", "en":"Tags"
    },
    "collapsabled": true
}
```

Ce layout ne passe pas.
Il faudrait qu'il puisse passer pour le bien de l'humanité rien de moins.
ça permettrait de donner un nom aux groupes multilignes

``` bash
TypeError: (layouts[name] || []).map is not a function
    at _getLayout (/home/pgi/dev/isari/server/lib/layouts.js:42:37)
    at name (/home/pgi/dev/isari/server/lib/layouts.js:96:12)
    at Array.map (native)
    at getRowObject (/home/pgi/dev/isari/server/lib/layouts.js:77:22)
    at getRowArray (/home/pgi/dev/isari/server/lib/layouts.js:68:51)
    at getRowString (/home/pgi/dev/isari/server/lib/layouts.js:66:49)
    at row (/home/pgi/dev/isari/server/lib/layouts.js:60:10)
    at Array.map (native)
    at _getLayout (/home/pgi/dev/isari/server/lib/layouts.js:42:37)
    at getLayout (/home/pgi/dev/isari/server/lib/layouts.js:35:39)
    at module.exports.Router.get.req (/home/pgi/dev/isari/server/routes/layouts.js:11:17)
    at Promise.resolve.then (/home/pgi/dev/isari/server/lib/rest-utils.js:12:31)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by paulgirard** [comment]
Un workaround qui marche : 
dans le layout people 
```json
 {
        "fields": ["tags"],
        "label": {"fr":"Tags","en":"Tags"},
        "collapsabled": true
    }
```
dans layout.people.tags.json
```json
[
	  ["researchTheme", "discipline", "methods"],
	  ["erc", "aeres2012","hceres2017"],
	  "free"
]
```
